# CI de Nível 01 - Disparo Manual através de clique

name: "Execução Manual"

on:
  workflow_dispatch:
    inputs:
      ambiente_execucao:
        description: 'Escolha onde o teste vai rodar:'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

jobs:
  e2e-tests:
    runs-on: ${{ github.event.inputs.ambiente_execucao }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Instalando Yarn
        run: npm install -g yarn
            
      - name: Instalando dependências
        run: yarn
            
      - name: Instalando Browsers do Playwright
        run: yarn playwright install
            
      - name: Executando testes e2e
        run: yarn run e2e

      # Notificar via Discord, para funcionar tanto no Windows, quanto no Linux
      - name: Notificar Discord
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: 'A execução do pipeline finalizou!'
          username: 'GitHub Actions Bot'