# CI de Nível 01 - Disparo manual através de clique

# nome do pipeline
name: "Execução Manual"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
    workflow_dispatch:

# tarefas dentro da pipeline = jobs

jobs:
    #nome do job
    e2e-tests:
        # máquina onde o job vai rodar
        runs-on: [self-hosted, meu-computador]

        # passos do job
        steps:
            # clone do projeto
            - name: Checkout code
              uses: actions/checkout@v4

            # Instalação das dependências
            - name: Instalando dependências
              run: yarn install

            # Instalação dos Browsers do Playwright
            - name: Instalando Browsers do Playwright
              run: yarn playwright install --with-deps

            # Executar os testes e2e
            - name: Executando testes e2e
              run: yarn run e2e

            # Notificação do Discord
            - name: Notificar no Discord
              uses: rjstone/discord-webhook-notify@v1
              if: always() # Continua garantindo o envio mesmo se o teste falhar
              with:
                severity: info
                details: 'O pipeline do projeto pgats-ci terminou de rodar!'
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}  
            
