# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: "Execução Manual"

# gatilhos / triggers - regras de disparo
on:
  workflow_dispatch:
    # menu de seleção do ambiente para execução dos testes
    inputs:
      ambiente_execucao:
        description: 'Escolha onde o teste vai rodar:'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - self-hosted

# tarefas dentro da pipeline = jobs
jobs:
  # nome do job
  e2e-tests:
    # github vai ler a escolha
    runs-on: ${{ github.event.inputs.ambiente_execucao }}

    # passos do job
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn
            
      # instalação das dependências
      - name: Instalando dependências
        run: yarn
            
      # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install
            
      # executar os testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

      # notificação para o Discord
      - name: Notificar Discord
        if: always()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: 'A execução do pipeline finalizou com: ${{ job.status }}'